<?php

/**
 * @file
 * Contains reward_migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function reward_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the reward_migrate module.
    case 'help.page.reward_migrate':
      $output = '';
      $output .= '<h3>' . t('Reward Migrate') . '</h3>';
      $output .= '<p>' . t('The import will allow a CSV file to create the Reward content for the site.') . '</p>';
      return $output;

    default:
  }
}
